import assert from 'node:assert/strict'
import {sampleRack,createThreats,addThreatSample,sampleThreats} from './threats.js'
import {emptyBoard,Lexicon,applyMove} from './game.js'
const pool=['A','A','B','?']
assert.deepEqual(sampleRack(pool,4,()=>0),pool)
assert.deepEqual(pool,['A','A','B','?'])
assert.deepEqual(sampleRack(pool,0),[])
const move=(score,indices)=>({score,placements:indices.map(i=>({r:Math.floor(i/15),c:i%15}))})
const result=createThreats()
addThreatSample(result,[move(10,[0,1]),move(40,[0]),move(0,[2])])
addThreatSample(result,[move(20,[1])])
assert.equal(result.samples,2)
assert.deepEqual(result.hits.slice(0,3),[1,2,1])
assert.deepEqual(result.scores.slice(0,3),[40,30,0])
assert.equal(result.bestTotal,60)
assert.equal(result.examples[0].score,40)
addThreatSample(result,[])
assert.equal(result.samples,3)
assert.equal(result.any,2)
const board=emptyBoard(),lex=new Lexicon(['AT','TA'])
const exact=sampleThreats(board,['A','T'],2,lex,createThreats())
assert.equal(exact.hits[7*15+7],1)
assert.equal(exact.samples,1)
const blank=sampleThreats(board,['?','T'],2,lex,createThreats())
assert.equal(blank.any,1)
assert.ok(blank.examples[112].placements.some(p=>p.blank))
const preview=applyMove(board,[{r:7,c:7,letter:'A'},{r:7,c:8,letter:'T'}])
const after=sampleThreats(preview,['A','T'],2,lex,createThreats())
assert.equal(after.hits[112],0)
assert.equal(after.hits[113],0)
assert.equal(board[7][7],null)
console.log('Threat sampling tests passed')
